spring:
  application:
    name: tg-updates-receiver
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 180000
        request.timeout.ms: 20000
        linger.ms: 20
      retries: 3
      compression-type: lz4
  config:
    import: file:config/config.yml
  threads:
    virtual:
      enabled: true
