bots:
  configs:
    - username: "" # Идентификатор бота. Используется в качестве URI HTTP метода принимающего апдейты для вебхуков(/webhook/{id}), а также в логах для идентификации.
      maxConnections: "" # Максимальное количество одновременных запросов.
      allowedUpdates: "" # Список допустимых типов апдейтов.
      token: "" # Токен бота.
      secret: "" # Секрет, отправляемый сервером телеграма в запросе.
      updateDeliveryMethod: "" # Способ получения апдейтов: POLLING, WEBHOOK. По умолчанию POLLING.
      ip: "" # IP адрес сервера, на котором расположен бот. Используется для WEBHOOK.
      topic: "" # Наименование кафка топика, в который производитель будет помещать пришедшие апдейты.
      dropPendingUpdatesOnStart: "" # Сбрасывать ли накопившиеся апдейты на серверах телеграма при старте бота.
      dropPendingUpdatesOnShutdown: "" # Сбрасывать ли накопившиеся апдейты на серверах телеграма при выключении бота.
spring:
  kafka:
    bootstrap-servers: # Сервера, на которых развернуты брокеры кафки.
app:
  url: "" # Абсолютный URL-адрес с использованием доменного имени, по которому можно обратиться к данному приложению.
  polling:
    queue:
      capacity: "" # Размер очереди апдейтов в POLLING ботах.